from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('signup/', views.signup_view, name='signup'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('about/',views.about_view,name='about'),
    path('contact/',views.contact_view, name='contact'),
    path('privacy/',views.privacy_view, name='privacy'),
    path('terms/',views.terms_view, name='terms'),
    path('cookie/',views.cookie_view, name='cookie'),
    path('copyright/',views.copy_view, name='copy'),
    path('help/',views.help_view, name='help'),
    path('report/',views.report_view, name='report'),
    path('features/',views.features_view,name='features'),
    path('404/',views.error_view,name="404"),
    path('pricing/',views.pricing_view,name="pricing"),
    path('reviews/',views.reviews_view,name="reviews"),
    path('accessibility/',views.accessibility_view,name="accessibility"),
    path('gallery/',views.gallery_view,name="gallery"),
    path('careers/',views.careers_view,name="careers"),
    path('creators/',views.creators_view,name="creators"),
    path('adcenter/',views.ad_center_view,name="adcenter"),
    path('support/',views.support_view,name="support"),
    path('press/',views.press_view,name="press"),
    path('developers/',views.developers_view,name="developers"),
    path('documentation/',views.documentation_view,name="documentation"),
    path('sitemap/',views.sitemap_view,name="sitemap"),
    path('feedback/',views.feedback_view,name="feedback"),
    path('events/',views.event_view,name="events"),
    path('community/',views.community_view,name="community"),
    path('disclaimer/',views.disclaimer_view,name="disclaimer"),
    path('downloads/',views.downloads_view,name="downloads"),
    path('partners/',views.partners_view,name="partners"),
    path('services/',views.services_view,name="services"),
    path('status/',views.status_view,name="status"),
    path('news/',views.news_view,name="news"),
    path('addition/',views.addition,name="addition"),
    path('substraction/',views.substraction,name='substraction'),
    path('multiply/',views.multipicatiion,name='multiply'),
    path('division/',views.division,name="division"),
    path('square/',views.square,name='square'),
    path("profile/", views.view_profile, name="view_profile"),
    path("profile/edit/", views.edit_profile, name="edit_profile"),
]   